"""
Game constants and configuration.
"""

# World bounds
WORLD_WIDTH = 800
WORLD_HEIGHT = 600

# Physics
PLAYER_SPEED = 200.0  # units per second
PLAYER_RADIUS = 15  # pixels for rendering
DASH_SPEED_MULTIPLIER = 3.5
DASH_DURATION = 0.12
DASH_COOLDOWN = 1.0
CONTACT_DAMAGE_PER_SEC = 20.0
DASH_CONTACT_DAMAGE_MULTIPLIER = 2.0
DAMAGE_BOOST_MULTIPLIER = 1.5
RESPAWN_HEALTH = 100.0
RESPAWN_DELAY_TICKS = 60
KILLS_TO_WIN = 5
MATCH_DURATION_SECS = 120.0
MATCH_OVER_DISPLAY_SECS = 5.0
INVINCIBILITY_DURATION_TICKS = 80
DAMAGE_BOOST_DURATION_TICKS = 80
DASH_COOLDOWN_BUFF_DURATION_TICKS = 100
DASH_COOLDOWN_REDUCTION_FACTOR = 0.45
MODIFIER_RADIUS = 12
MODIFIER_PICKUP_RADIUS = 22
MAX_MODIFIERS = 3
MODIFIER_SPAWN_INTERVAL_TICKS = 120
MODIFIER_INVINCIBILITY = 1
MODIFIER_DAMAGE_BOOST = 2
MODIFIER_DASH_COOLDOWN = 3
EFFECT_FLAG_INVINCIBILITY = 0x01
EFFECT_FLAG_DAMAGE_BOOST = 0x02
EFFECT_FLAG_DASH_COOLDOWN = 0x04

# Network defaults
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 9000
DEFAULT_TICK_RATE = 20  # Server ticks per second
DEFAULT_BUFFER_SIZE = 4096

# Timeouts
CLIENT_TIMEOUT = 10.0  # Seconds before disconnecting idle client
CONNECT_RETRY_INTERVAL = 1.0
PING_INTERVAL = 1.0  # Seconds between pings

# Interpolation
INTERPOLATION_TICKS = 2  # Render N ticks behind server time

# Input redundancy
INPUT_REDUNDANCY = 3  # Send last N inputs in each packet

# Reliable channel
RELIABLE_MAX_RETRIES = 5
RELIABLE_RETRY_INTERVAL = 0.2
